### ISSUE TITLE
clock_gettime only available on Mac OS X 10.12

### ISSUE THREAD

**Issue by gcartier** [gambit/gambit#293]
Running an application build with Gambit 4.8.8 on Mac OS X Yosemite 10.10 results in the following error (see NOTE at the end):

$ /Applications/Yownu.app/Contents/MacOS/Yownu 
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/Yownu.app/Contents/Apps/Yownu.app/Contents/MacOS/Yownu (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/Yownu.app/Contents/Apps/Yownu.app/Contents/MacOS/Yownu (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

- - - - - - - - - - - - -

NOTE: I rebuilt Gambit from scratch with export MACOSX_DEPLOYMENT_TARGET=10.9 expecting this to fix the problem but strangely the problem is still present.

**Comment by ober** [comment]
Same issue on 10.11

**Comment by feeley** [comment]
Fixed by commit a44589a9a5141b478dd6da25ae04cf94348acec1 .

**Comment by ober** [comment]
Still breaking here for me on 10.11 https://gist.github.com/8f65b157cdab517629bf25671b6b3176

**Comment by gcartier** [comment]
Same for me, configure still thinks clock_gettime is available even though I exported MACOSX_DEPLOYMENT_TARGET=10.9

**Comment by feeley** [comment]
It is likely that the problem is due to the bootstrapping process. The "make current-gsc-boot" will use the "configure" and "lib/os.h" of the most recent release, but that does not contain the patch I just did. This problem should go away when I create the next release.

You might have success with applying the latest patch to the file boot/lib/os.h ... or simply edit boot/include/config.h to remove the "#define HAVE_CLOCK_GETTIME".

**Comment by ober** [comment]
Works here

**Comment by feeley** [comment]
@ober Can you give a bit more detail on your setup.  If I understand correctly you are trying to build on MacOS 10.11 and that is generating errors during the build process.  I believe @gcartier has a different problem... building on MacOS 10.12 works, but executing on MacOS 10.10 gives the dynamic linking error (because 10.10 does not export ```clock_gettime```). So I still don't understand why when building on 10.11 the old configure script thinks that ```clock_gettime``` is available).

**Comment by ober** [comment]
10.11 also lacks clock_gettime and so I get the same error he did. I applied your fixes to boot/lib/os.h and removed the define from both config.h and 'make current-gsc-boot' now completes and I can install it and use it.

**Comment by feeley** [comment]
@ober So previously you were building on 10.11 and getting an error on the 'make current-gsc-boot'? If that is the case I don't understand why the configure script thinks that ```clock_gettime``` is available on 10.11.  I understand @gcartier's problem of building on 10.12 (where ```clock_gettime``` is available) and executing on 10.10 (where it is not available).

**Comment by ober** [comment]
I got the same error he did, and it was building as if it had clock_gettime. Although I had not used the target variable previously.

**Comment by feeley** [comment]
OK, anyway this should disappear when the next release comes out.  Soon I hope...
