### ISSUE TITLE
Git master fails to build on MacOS Mojave

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#400]
Git master at 3b5f74f fails to build on MacOS 10.14.6 with the default `./configure && make`. Build log: https://misc.lassi.io/2019/gambit-mojave-3b5f74f.log

**Comment by lassik** [comment]
The most obvious errors are along the lines of ```warning: implicit declaration of function '___CHARALPHABETICP' is invalid in C99 [-Wimplicit-function-declaration]
   ___IF(___NOT(___CHARALPHABETICP(___R4)))```

**Comment by feeley** [comment]
This is a bootstrapping problem.  It should not happen if you make a fresh clone of the Gambit repo or if you `rm -rf boot gsc-boot;make`.  In any case this issue will go away at the next release.
