### ISSUE TITLE
4.9.4 Release tarball contains wrong version

### ISSUE THREAD

**Issue by leahneukirchen** [gambit/gambit#731]
I think in https://github.com/gambit/gambit/commit/a2ecdae82107bce5f2d15ed3c926612024c5914c you should have changed it to "v4.9.4"?

**Comment by belmarca** [comment]
Hi @leahneukirchen , can you provide a direct link to the release? Did you fetch it from GitHub?

**Comment by leahneukirchen** [comment]
Yeah, https://github.com/gambit/gambit/archive/v4.9.4.tar.gz

**Comment by feeley** [comment]
Indeed the wrong version was put in the stamp file of the release.  I'll have to update the makefiles so this problem doesn't happen for the next release.  I'm ambivalent on whether the tar file should be patched because it would no longer match the git history.  Perhaps v4.9.5 should be released soon instead.

**Comment by leahneukirchen** [comment]
I patch it locally for now, thanks. :)

There are lots of version numbers all over the code, it may be good to centralize them.

**Comment by ChillPC** [comment]
Hello everybody.
It would be really helpful to update the tar @feeley . I created my package in guix taking the `tar.gz` from github to have the version `4.9.4` with r7rs support (and because it is really handy). If I copy the example of the [section "3.4.1 Building an executable program" of the manual](https://gambitscheme.org/latest/manual/#Building-an-executable-program), I get:

```sh
$ gsc -link m2 m3 && gcc m1.o m2.o m3.c m3_.o -lgambit -lm -ldl -lutil
m2:
m3:
In file included from /usr/include/gambit.h:15,
                 from m3.c:44:
/usr/include/gambit-not409003.h:1:2: error: #error "The version indicated in ___VERSION is not support
ed by gambit.h"
    1 | #error "The version indicated in ___VERSION is not supported by gambit.h"
      |  ^~~~~
/usr/include/gambit-not409003.h:2:2: error: #error "You are probably compiling C code generated by a G
ambit compiler earlier or later than v4.9.3"
    2 | #error "You are probably compiling C code generated by a Gambit compiler earlier or later than
 v4.9.3"
      |  ^~~~~
/usr/include/gambit-not409003.h:3:2: error: #error "___VERSION will be set to 409003 to reduce other e
rrors"
    3 | #error "___VERSION will be set to 409003 to reduce other errors"
      |  ^~~~~
m3.c:46:1: warning: return type defaults to 'int' [-Wimplicit-int]
   46 | ___NEED_SYM(___S_m3)
      | ^~~~~~~~~~~
m3.c: In function '___NEED_SYM':
m3.c:47:1: error: expected declaration specifiers before '___NEED_SYM'
   47 | ___NEED_SYM(___S_m3_23_)
      | ^~~~~~~~~~~
m3.c:46:1: warning: type of '___S_m3' defaults to 'int' [-Wimplicit-int]
   46 | ___NEED_SYM(___S_m3)
      | ^~~~~~~~~~~
```

**Comment by feeley** [comment]
This is fixed by ed7fa8abfacdd0791cc7ae74a7c892027491b78b (for release v4.9.5). I'll wait until v4.9.5 is released before closing.

**Comment by leahneukirchen** [comment]
Works in 4.9.5, thanks!
